export const branches = [
  {
    id: 'ang-mo-kio',
    name: 'Ang Mo Kio (Flagship)',
    address: 'Block 709 Ang Mo Kio Ave 8, #01-2609',
    postalCode: 'Singapore 560709',
    region: 'north',
    phone: '+65 6234 5678',
    hours: 'Mon-Sun: 6:00am - 8:00pm',
    googleMapsUrl: 'https://goo.gl/maps/example1',
    coordinates: { lat: 1.3719, lng: 103.8485 },
    isflagship: true,
    highlights: [
      'Original location since 2013',
      'Right beside NTUC Fairprice',
      'Near Masjid Al-Muttaqin',
      'Air-conditioned dining',
    ],
    story: 'Where it all began! A stone\'s throw from Ang Mo Kio MRT, beside NTUC Fairprice. Our founders chose this spot to serve the Malay-Muslim community in the heart of town.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop',
  },
  {
    id: 'bukit-batok',
    name: 'Bukit Batok',
    address: 'Block 155 Bukit Batok St 11, #01-322',
    postalCode: 'Singapore 650155',
    region: 'west',
    phone: '+65 6567 8901',
    hours: 'Mon-Sun: 6:00am - 8:00pm',
    googleMapsUrl: 'https://goo.gl/maps/example2',
    coordinates: { lat: 1.3497, lng: 103.7464 },
    highlights: [
      'Family-friendly neighborhood',
      'Spacious seating',
      'Popular for breakfast',
      'Near HDB heartlands',
    ],
    story: 'Serving West side families with the same authentic flavors. Popular breakfast spot for residents heading to work.',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&h=600&fit=crop',
  },
  {
    id: 'hougang',
    name: 'Hougang (Kang Kar Mall)',
    address: '100 Hougang Avenue 10, #01-03',
    postalCode: 'Singapore 530100',
    region: 'east',
    phone: '+65 6345 6789',
    hours: 'Mon-Sun: 6:00am - 8:00pm',
    googleMapsUrl: 'https://goo.gl/maps/example3',
    coordinates: { lat: 1.3742, lng: 103.8960 },
    highlights: [
      'Inside Kang Kar Mall',
      'Convenient parking',
      'Near Hougang MRT',
      'Weekend family spot',
    ],
    story: 'Bringing our legendary sambal to the East! Conveniently located in Kang Kar Mall with ample parking.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop',
  },
  {
    id: 'toa-payoh',
    name: 'Toa Payoh',
    address: '470 Lorong 6 Toa Payoh, #02-70',
    postalCode: 'Singapore 310470',
    region: 'central',
    phone: '+65 6789 0123',
    hours: 'Mon-Sun: 6:00am - 8:00pm',
    googleMapsUrl: 'https://goo.gl/maps/example4',
    coordinates: { lat: 1.3326, lng: 103.8474 },
    highlights: [
      'Central location',
      'Mature estate favorite',
      'Quick lunch spot',
      'Generous portions',
    ],
    story: 'A favorite among Toa Payoh residents. Known for quick service during lunch rush without compromising on taste.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop',
  },
  {
    id: 'yishun',
    name: 'Yishun (KTPH Hospital)',
    address: '90 Yishun Central, #01-12',
    postalCode: 'Singapore 768828',
    region: 'north',
    phone: '+65 6890 1234',
    hours: 'Mon-Sun: 6:00am - 8:00pm',
    googleMapsUrl: 'https://goo.gl/maps/example5',
    coordinates: { lat: 1.4241, lng: 103.8384 },
    highlights: [
      'At KTPH Hospital',
      'Serves patients & visitors',
      'Comfort food when needed most',
      'Halal certified hospital outlet',
    ],
    story: 'Bringing comfort through food to hospital visitors and staff. A taste of home when you need it most.',
    image: 'https://images.unsplash.com/photo-1744168222850-85b5e5e9aa24?q=80&w=1470&auto=format&fit=crop',
  },
  {
    id: 'woodlands',
    name: 'Woodlands (Central Kitchen)',
    address: '15 Woodlands Loop, #04-27',
    postalCode: 'Singapore 738322',
    region: 'north',
    phone: '+65 6901 2345',
    hours: 'Catering & Wholesale Only',
    googleMapsUrl: 'https://goo.gl/maps/example6',
    coordinates: { lat: 1.4500, lng: 103.8060 },
    isCentralKitchen: true,
    highlights: [
      'Not open for dine-in',
      'Catering operations',
      'Bulk orders',
      'Maintains quality across all outlets',
    ],
    story: 'Our central kitchen ensures every branch serves the same quality food. Contact us for catering & wholesale inquiries.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
  },
]

export type Branch = typeof branches[0]