export const menuCategories = [
  {
    id: 'signatures',
    name: 'Signature Dishes',
    icon: '⭐',
    description: 'Our most loved dishes - the ones that keep customers coming back!',
  },
  {
    id: 'nasi-padang',
    name: 'Nasi Padang',
    icon: '🍛',
    description: 'Our flagship! Choose from 20+ freshly prepared dishes - mix and match your favorites',
  },
  {
    id: 'rice',
    name: 'Rice Dishes',
    icon: '🍚',
    description: 'Hearty rice meals with authentic Malay flavors',
  },
  {
    id: 'noodles',
    name: 'Noodles',
    icon: '🍜',
    description: 'Traditional noodle dishes prepared fresh daily',
  },
  {
    id: 'mains',
    name: 'Main Dishes',
    icon: '🍖',
    description: 'Protein-rich mains perfect for sharing',
  },
  {
    id: 'sides',
    name: 'Sides & Vegetables',
    icon: '🥗',
    description: 'Complement your meal with traditional sides',
  },
  {
    id: 'drinks',
    name: 'Drinks',
    icon: '🥤',
    description: 'Refresh yourself with our selection',
  },
]

export const menuItems = [
  // SIGNATURE DISHES
  {
    id: 'secret-sambal',
    name: 'Secret Sambal',
    category: 'signatures',
    price: 'FREE',
    description: 'The legendary condiment everyone talks about. Ask for it at the counter!',
    story: '"We can never have enough of that!!" - Customer favorite that gives that "oomph" to every dish',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Spicy', 'Vegetarian'],
    isSignature: true,
    customerQuote: 'The best-kept secret and crowd-drawer!',
  },
  {
    id: 'mutton-rendang',
    name: 'Mutton Rendang',
    category: 'signatures',
    price: '9.20',
    description: 'Slow-cooked for 6 hours until fork-tender in aromatic spices',
    story: 'Our most improved dish! Customers say it\'s "outstanding, tender, flavorful, and perfectly spiced"',
    image: 'https://images.unsplash.com/photo-1620700791277-d2cec5be17ef?q=80&w=774&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
    isSignature: true,
    customerQuote: 'The beef rendang was outstanding!',
  },
  {
    id: 'ayam-penyet',
    name: 'Ayam Penyet',
    category: 'signatures',
    price: '8.50',
    description: 'Indonesian-style crispy fried chicken served with our signature sambal',
    story: '"Super crispy outside, super juicy inside" - served with our legendary sambal that elevates it to the next level',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&h=400&fit=crop',
    dietary: ['Halal'],
    isSignature: true,
    customerQuote: 'Super crispy, meat super juicy!',
  },
  {
    id: 'nasi-padang-set',
    name: 'Nasi Padang',
    category: 'signatures',
    price: '6.80',
    priceRange: 'From $6.80',
    description: 'Choose from 20+ freshly prepared items - the dish we\'re famous for!',
    story: 'Generous portions that "make you full for the rest of the day!" Our most popular item since 2013',
    image: 'https://images.unsplash.com/photo-1666239308347-4292ea2ff777?q=80&w=1470&auto=format&fit=crop',
    dietary: ['Halal', 'Customizable'],
    isSignature: true,
    customerQuote: 'Always packed during lunch!',
  },

  // NASI PADANG OPTIONS
  {
    id: 'chicken-rendang',
    name: 'Chicken Rendang',
    category: 'nasi-padang',
    price: '6.80',
    description: 'Tender chicken in rich coconut-based curry',
    image: 'https://images.unsplash.com/photo-1620700791277-d2cec5be17ef?q=80&w=774&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'ayam-masak-merah',
    name: 'Ayam Masak Merah',
    category: 'nasi-padang',
    price: '6.80',
    description: 'Red-cooked chicken in tomato and chili gravy - a crowd favorite',
    story: 'One of our signature dishes we\'re constantly improving on',
    image: 'https://images.unsplash.com/photo-1696340034876-6245523babfa?q=80&w=774&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'asam-fish',
    name: 'Asam Fish',
    category: 'nasi-padang',
    price: '8.50',
    description: 'Tamarind fish curry - our namesake dish!',
    story: 'Named after the tamarind ("asam") that makes Malay cooking special',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'sambal-prawn',
    name: 'Sambal Prawn',
    category: 'nasi-padang',
    price: '9.20',
    description: 'Fresh prawns in spicy sambal sauce',
    image: 'https://images.unsplash.com/photo-1669385184435-233842a157f3?q=80&w=774&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'beef-rendang',
    name: 'Beef Rendang',
    category: 'nasi-padang',
    price: '9.20',
    description: 'Slow-cooked beef in aromatic spices and coconut',
    image: 'https://images.unsplash.com/photo-1620700791277-d2cec5be17ef?q=80&w=774&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'cuttlefish-curry',
    name: 'Cuttlefish Curry',
    category: 'nasi-padang',
    price: '9.20',
    description: 'Tender cuttlefish in rich curry sauce',
    image: 'https://images.unsplash.com/photo-1708782340377-882559d544fb?q=80&w=1480&auto=format&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },

  // RICE DISHES
  {
    id: 'nasi-lemak',
    name: 'Nasi Lemak',
    category: 'rice',
    price: '7.80',
    description: 'Fragrant coconut rice with sambal, egg, peanuts & anchovies',
    image: 'https://images.unsplash.com/photo-1593560704563-f176a2eb61db?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'nasi-goreng',
    name: 'Nasi Goreng',
    category: 'rice',
    price: '7.80',
    description: 'Indonesian fried rice with egg and chicken',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },

  // NOODLES
  {
    id: 'mee-rebus',
    name: 'Mee Rebus',
    category: 'noodles',
    price: '7.80',
    description: 'Yellow noodles in sweet potato gravy',
    story: 'The "sweetness of gravy is the main draw" - a customer favorite!',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    dietary: ['Halal'],
    customerQuote: 'Sweetness of gravy is the main draw',
  },
  {
    id: 'mee-siam',
    name: 'Mee Siam',
    category: 'noodles',
    price: '7.80',
    description: 'Spicy & tangy rice vermicelli',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Spicy'],
  },
  {
    id: 'mee-soto',
    name: 'Mee Soto',
    category: 'noodles',
    price: '7.80',
    description: 'Yellow noodles in aromatic chicken broth',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'lontong',
    name: 'Lontong',
    category: 'noodles',
    price: '7.80',
    description: 'Compressed rice cakes in coconut curry',
    story: 'Featured at our charity event - Ultimate Hawker Fest 2014!',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Vegetarian'],
  },

  // MAINS
  {
    id: 'ayam-goreng',
    name: 'Ayam Goreng',
    category: 'mains',
    price: '6.80',
    description: 'Crispy fried chicken with traditional spices',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'ikan-goreng',
    name: 'Ikan Goreng',
    category: 'mains',
    price: '8.50',
    description: 'Crispy fried fish with turmeric',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },

  // SIDES & VEGETABLES
  {
    id: 'tofu-tempeh-long-bean',
    name: 'Stir-Fried Tofu, Tempeh & Long Bean',
    category: 'sides',
    price: '5.50',
    description: 'Vegetarian favorite in savory sauce',
    story: '"The champion... we are converted!" - Even meat-lovers rave about this one',
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Vegetarian'],
    customerQuote: 'The champion!',
  },
  {
    id: 'sayur-lodeh',
    name: 'Sayur Lodeh',
    category: 'sides',
    price: '5.50',
    description: 'Mixed vegetables in coconut curry',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Vegetarian'],
  },
  {
    id: 'rojak',
    name: 'Rojak',
    category: 'sides',
    price: '6.50',
    description: 'Fruit & vegetable salad with peanut sauce',
    story: '"We love their rojak too!" - Fresh and flavorful',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop',
    dietary: ['Halal', 'Vegetarian'],
  },

  // DRINKS
  {
    id: 'teh-tarik',
    name: 'Teh Tarik',
    category: 'drinks',
    price: '2.50',
    description: 'Pulled milk tea - a Singaporean classic',
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'kopi-o',
    name: 'Kopi O',
    category: 'drinks',
    price: '2.50',
    description: 'Black coffee with sugar',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'milo-dinosaur',
    name: 'Milo Dinosaur',
    category: 'drinks',
    price: '3.50',
    description: 'Iced Milo with extra Milo powder on top',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
  {
    id: 'fresh-juice',
    name: 'Fresh Juice',
    category: 'drinks',
    price: '3.50',
    description: 'Daily selection of fresh fruit juices',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&h=400&fit=crop',
    dietary: ['Halal'],
  },
]

export type MenuItem = typeof menuItems[0]
export type MenuCategory = typeof menuCategories[0]